from typing import Protocol, Dict, Any, Optional

class IColorMath(Protocol):
    def hex_to_rgb(self, hex_code: str) -> tuple: ...
    def rgb_to_hsl(self, r: int, g: int, b: int) -> tuple: ...
    def calculate_distance(self, hsl1: tuple, hsl2: tuple) -> float: ...

class ITranslationService(Protocol):
    def translate(self, text: str, source: str, target: str) -> str: ...